######################################################
# Platform metadata for releases, POM generation, etc.
######################################################
group=com.microfish.it.account
version=7.3.8-SNAPSHOT
projectUrl=https://www.apereo.org/projects/cas
projectInceptionYear=2004
projectScmUrl=scm:git@github.com:kenny5he/cas.git
projectLicenseName=The Apache Software License, Version 2.0
projectLicenseUrl=https://www.apache.org/licenses/LICENSE-2.0.txt
projectLicenseDistribution=repo
projectIssueSystem=GitHub
projectIssueUrl=https://github.com/apereo/cas/pulls
releaseRepositoryUrl=https://ossrh-staging-api.central.sonatype.com/service/local/
#snapshotsRepositoryUrl=https://central.sonatype.com/repository/maven-snapshots/
snapshotsRepositoryUrl=https://packages.aliyun.com/69319767876b90de1aacdb6e/maven/2628060-snapshot-x0npm3
############################
# Gradle settings
############################
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xms1024m -Xmx8048m \
  -XX:+EnableDynamicAgentLoading -XX:SoftRefLRUPolicyMSPerMB=0 \
  -XX:ReservedCodeCacheSize=128m -XX:TieredStopAtLevel=1 \
  --add-opens java.base/java.io=ALL-UNNAMED
org.gradle.unsafe.configuration-cache=true
org.gradle.configuration-cache.parallel=true
############################################
# SonarQube settings for code quality checks
############################################
sonarHostUrl=https://sonarcloud.io
sonarOrganization=apereo
sonarProjectName=cas
#######################
# Platform SDK versions
#######################
sourceCompatibility=21
targetCompatibility=21
################
# Gradle plugins
################
develocityApereoServerUrl=https://develocity.apereo.org/
