#Query Database Authentication \u6570\u636E\u5E93\u67E5\u8BE2\u6821\u9A8C\u7528\u6237\u540D\u5F00\u59CB -->> QueryJdbcAuthenticationProperties.java
cas.authn.jdbc.query[0].sql=select * from cas_user where user_name=?
cas.authn.jdbc.query[0].fieldPassword=password
cas.authn.jdbc.query[0].fieldExpired=expired
cas.authn.jdbc.query[0].fieldDisabled=status
cas.authn.jdbc.query[0].principal-attribute-list[0]=nike_name
cas.authn.jdbc.query[0].principal-attribute-list[1]=first_name
cas.authn.jdbc.query[0].principal-attribute-list[2]=last_name
cas.authn.jdbc.query[0].principal-attribute-list[3]=gender
cas.authn.jdbc.query[0].principal-attribute-list[4]=phone
cas.authn.jdbc.query[0].principal-attribute-list[5]=email
cas.authn.jdbc.query[0].principal-attribute-list[6]=favicon_id
cas.authn.jdbc.query[0].dialect=org.hibernate.dialect.MySQL5Dialect
cas.authn.jdbc.query[0].driverClass=com.mysql.jdbc.Driver
cas.authn.jdbc.query[0].url=jdbc:mysql://gz-cynosdbmysql-grp-dxzq8rav.sql.tencentcdb.com:25025:25025/cas
cas.authn.jdbc.query[0].user=mfl
cas.authn.jdbc.query[0].password=Gt^&V90ZB^aiK1Wl
# \u6CE8\uFF1A\u7ECF\u9A8C\u8BC1\u8BBE\u4E3AUPPERCASE\uFF0C\u5219\u8F93\u5165\u7684\u5E10\u53F7\u4F1A\u88AB\u8F6C\u6362\u6210\u5927\u5199\uFF0C\u6570\u636E\u5E93\u91CC\u7684\u5E10\u53F7\u4E5F\u4F1A\u8F6C\u6362\u6210\u5927\u5199\u3002\u82E5\u4E3ALOWERCASE\u5219\u5168\u90E8\u8F6C\u6362\u6210\u5C0F\u5199\u3002
cas.authn.jdbc.query[0].principalTransformation.caseConversion=LOWERCASE
###\u9ED8\u8BA4\u52A0\u5BC6\u7B56\u7565\uFF0C\u901A\u8FC7encodingAlgorithm\u6765\u6307\u5B9A\u7B97\u6CD5\uFF0C\u9ED8\u8BA4NONE\u4E0D\u52A0\u5BC6
# PasswordEncoder.type \u679A\u4E3E\u7C7B\u578B\u53D6\u503C PasswordEncoderProperties$PasswordEncoderTypes.java
#cas.authn.jdbc.query[0].passwordEncoder.type=BCRYPT
#cas.authn.jdbc.query[0].passwordEncoder.type=DEFAULT
#cas.authn.jdbc.query[0].passwordEncoder.type=PBKDF2
#cas.authn.jdbc.query[0].passwordEncoder.secret=
#cas.authn.jdbc.query[0].passwordEncoder.characterEncoding=UTF-8
#cas.authn.jdbc.query[0].passwordEncoder.encodingAlgorithm=MD5
# \u53C2\u8003: https://blog.csdn.net/hansonjan/article/details/106218544