cas.theme.name=Microfoolish Theme
cas.theme.description=Microfoolish - Central Authentication Service

cas.standard.css.file=/themes/microfoolish/css/cas.css
cas.standard.js.file=/themes/microfoolish/js/cas.js
cas.logo.file=/themes/microfoolish/images/logo.svg
cas.favicon.file=/themes/microfoolish/images/favicon.ico

cas.drawer-menu.enabled=false
cas.notifications-menu.enabled=false
cas.login-form.enabled=true
cas.pm-links.enabled=true
cas.public-workstation.enabled=false
cas.warn-on-redirect.enabled=false