cas.theme.name=Theme
cas.theme.description=Central Authentication Service

cas.standard.css.file=/themes/yywx/css/cas.css
cas.standard.js.file=/themes/yywx/js/cas.js
cas.logo.file=/themes/yywx/images/logo.svg
cas.favicon.file=/themes/yywx/images/favicon.ico

cas.drawer-menu.enabled=false
cas.notifications-menu.enabled=false
cas.login-form.enabled=true
cas.pm-links.enabled=false
